spring: 
   application: 
     name: shop # app name
   h2:
     console:
       enabled: true # h2控制台 http://localhost:8080/h2-console
   datasource: 
     driver-class-name: org.h2.Driver
#     url: jdbc:h2:~/test # in file 能持久儲存，但只能單一連線
     url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE # in memory 只能用h2-console操作
     username: sa
     password: 

# log level
logging: 
  level: 
    root: INFO
    "[uk.lazycat.shop]": DEBUG

mybatis:
  mapper-locations: classpath:mappers/**/*Mapper.xml

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

springdoc: 
  swagger-ui: 
    tryItOutEnabled: true # 預設try it out 已經點擊