spring: 
   application: 
     name: shop # app name
   h2:
     console:
       enabled: true # h2控制台 http://localhost:8080/h2-console
   datasource: 
     driver-class-name: org.h2.Driver
     url: jdbc:h2:~/test
     username: sa
     password: 

# log level
logging: 
  level: 
    root: INFO
    "[uk.lazycat.shop]": DEBUG

mybatis:
  mapper-locations: classpath:mappers/**/*Mapper.xml

springdoc: 
  swagger-ui: 
    tryItOutEnabled: true # 預設try it out 已經點擊