spring: 
   application: 
     name: shop # app name
   h2:
     console:
       enabled: true # h2控制台 http://localhost:8080/h2-console
   datasource: 
     driver-class-name: org.h2.Driver
     url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE # in memory 只能用h2-console操作、jdbc:h2:~/test # in file 能持久儲存，但只能單一連線
     username: sa
     password: 
h2.tcp.server.enabled: true # 是否啟用H2 tcp server

# log 設定
logging: 
  pattern.console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){magenta} | %clr(${LOG_LEVEL_PATTERN:%-5level}) | %clr(%-40.40logger{39}){cyan} | %msg%n"
  level: 
    root: INFO
    "[uk.lazycat.shop]": DEBUG

spring.output.ansi.enabled: ALWAYS # 彩色LOG

# mybatis 設定
mybatis:
  mapper-locations: classpath:mappers/**/*Mapper.xml

# swagger 設定
springdoc: 
  swagger-ui: 
    tryItOutEnabled: true # 預設try it out 已經點擊

# 自定義設定
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
